// Channel names only (no dependencies), so the sandboxed preload stays tiny.

export const INVOKE_CHANNELS = [
  'app:info',
  'app:openLogFolder',
  'app:openOutputFolder',
  'app:openLicence',
  'app:checkUpdates',
  'app:installUpdate',
  'setup:status',
  'setup:start',
  'setup:cancel',
  'jobs:list',
  'jobs:create',
  'jobs:pause',
  'jobs:resume',
  'jobs:cancel',
  'jobs:delete',
  'clips:list',
  'clips:update',
  'clips:reset',
  'clips:pickMusic',
  'clips:previewAutoEdit',
  'layouts:list',
  'layouts:save',
  'layouts:delete',
  'layouts:setDefault',
  'exports:list',
  'exports:start',
  'exports:cancel',
  'exports:show',
  'bestOf:list',
  'bestOf:start',
  'bestOf:cancel',
  'bestOf:show',
  'work:list',
  'taste:status',
  'taste:reset',
  'channelWatch:status',
  'channelWatch:set',
  'channelWatch:clear',
  'settings:getAutostart',
  'settings:setAutostart',
  'models:download',
  'models:remove'
] as const

export const EVENT_CHANNELS = [
  'setup:status',
  'jobs:changed',
  'exports:changed',
  'bestOf:changed',
  'app:update',
  'channelWatch:changed',
  'jobs:focus',
  'autoEditPreview:changed'
] as const
